# Generated by Django 4.2.11 on 2024-04-13 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        ('comments', '0004_alter_comments_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='news_id',
            field=models.ForeignKey(blank=True, db_column='news_id', on_delete=django.db.models.deletion.CASCADE, to='news.news', verbose_name='Новость'),
        ),
    ]
